# Further Exercises

Use R code to answer each of the following exercises.

## Exercise 1 {-}

A university offers 8 different statistics courses to its honours level students. The numbers of students in each course are as follows:

* There are three course which have 85 students enrolled
* There are two course which have 112 students enrolled
* There is one course with 108 students enrolled
* There is one course with 95 students enrolled
* There is one course with only 46 students enrolled

Suppose you were to randomly sample three of these statistics courses **with** replacement. What would the sampling distribution of the sample mean number of students enrolled, $\bar X$, be? What would the sampling distribution of the sample variance in the number of students enrolled, $S^2$, be?

Can you use your sampling distributions to find $E[\bar X]$, $\sigma_{\bar X}^2$ and $E[S^2]$?


## Exercise 2 {-}

Now suppose you want to randomly sample three of the above statistics courses **without** replacement. Find the sampling distribution of the sample mean number of students, $\bar X$ and the sampling distribution of the sample variance in the number of students enrolled, $S^2$.

Use these sampling distributions to find $E[\bar X]$, $\sigma_{\bar X}^2$ and $E[S^2]$.

How do these values compare to those found in Exercise 1?









