project:
  type: book
  output-dir: docs

book:
  title: "S2S Labs"
  chapters: 
    - index.qmd
  
format:
  html:
    theme: [cosmo, custom.scss]
    css: 
    - styles.css
    toc: true
    include-after-body: include/webex.js
    embed-resources: true

editor: source