{
  "hash": "774b96fe93af3a75afbbcfbbf4682181",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Statistical Analysis\"\n---\n\n\n\n\n\n\nIn this lab, we will formally answer the following **aims** in our statistical report.\n\n1.  Is there a difference between the mean yields of potatoes from fields that were fertilised and fields that were unfertilised?\n\n2.  Is there a difference between the mean yields of wheat from fields that were fertilised and fields that were unfertilised?\n\nIn order to do this, we need to learn some new methods of calculating **confidence intervals** which will allow us to calculate a 95% confidence interval for the difference between the mean yield in each case.\n\n## Difference in Population Means {#sec-diff}\n\n<!-- # Confidence Intervals for the Difference in Population Means -->\n\nIn general, when we have two independent random variables which both follow normal distributions, say $X\\sim N(\\mu_X,\\,\\sigma_X)$ and $Y\\sim N(\\mu_Y,\\,\\sigma_Y)$, it is often of interest to find a range of values for the difference between the population means, $\\mu_X$ and $\\mu_Y$. This range of values can be found using a confidence interval for $\\mu_X-\\mu_Y$, but we have to be aware of the variances of both distributions, as this can change the way the confidence interval is calculated. In order to construct these confidence intervals, random samples have to be drawn from the underlying distributions.\n\nWe will use the following notation in the formulae for confidence intervals for the difference in population means,\n\n- $n_X$: the size of the sample drawn from $X\\sim N(\\mu_X,\\,\\sigma_X)$.\n- $n_Y$: the size of the sample drawn from $Y\\sim N(\\mu_Y,\\,\\sigma_Y)$.\n- $x_1, x_2, \\ldots , x_{n_X}$: the sample taken from $X\\sim N(\\mu_X,\\,\\sigma_X)$ with sample mean $\\bar{x}$ and sample variance $s^2_X$.\n- $y_1, y_2, \\ldots , y_{n_Y}$: the sample taken from $Y\\sim N(\\mu_Y,\\,\\sigma_Y)$ with sample mean $\\bar{y}$ and sample variance $s^2_Y$.\n\n### Variances are known and equal (8.2.3) {#sec-known-equal}\n\nIn the case where the population variances of both distributions are known and are equal, that is $\\sigma_X^2=\\sigma_Y^2=\\sigma^2$, then a $(1-\\alpha)\\cdot100\\%$ confidence interval for the difference in the population means, $\\mu_X-\\mu_Y$, is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.11} \\label{eq:known-equal}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-z_{1-\\frac{\\alpha}{2}}\\cdot\\sigma\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+z_{1-\\frac{\\alpha}{2}}\\cdot\\sigma\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation} \n```\n\n:::\n\n------------------------------------------------------------------------\n\nYou can find the derivation of this result and some additional exercises in [Section 8.2.3](https://read.kortext.com/reader/pdf/92741/466){target=\"_blank\"} of *Probability and Statistics with R*.\n\nWe saw from the Exploratory Analysis completed in [Lab 8](https://moodle.gla.ac.uk/pluginfile.php/9502911/mod_resource/content/2/03-eda.html#aim-1){target=\"_blank\"} that the yields of potatoes from fertilised and unfertilised fields both seem to follow a normal distribution with approximately equal variances. To simplify our analysis at this stage, let's first assume that the population variances are known and are equal to $\\sigma^2_\\mbox{f}=\\sigma^2_\\mbox{uf}=4^2$.\n\nThat is, we are assuming that the yield of potatoes from fertilised fields follows a $N(\\mu_\\mbox{f},4^2)$ distribution, and the yield of potatoes from unfertilised fields follows a $N(\\mu_\\mbox{uf}, 4^2)$ distribution.\n\nNow we are ready to compute a 95% confidence interval for the difference in population mean yields of potatoes from fields that were fertilised and fields that were unfertilised using Equation \\eqref{eq:known-equal}. That is, a confidence interval for $\\mu_\\mbox{f}-\\mu_\\mbox{uf}$. There a few different ways we could do this in R.\n\n:::{.example}\n::::{.example-header}\nMethod 1: Using R as a calculator\n::::\n::::{.example-container}\nIn order to use Equation \\eqref{eq:known-equal} above, there are a few values we need to find. We have already assumed that $\\sigma=4$, and we know that $n_X=130$ and $n_Y=80$. We can save these values in R using the code below.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 4\nnx <- 130\nny <- 80\n```\n:::\n\n:::\n\nThat leaves us to find $\\bar x$, $\\bar y$ and $z_{1-\\frac{\\alpha}{2}}$, the $(1-\\frac{\\alpha}{2})$^th^ quantile from the standard normal distribution. In our case, because we are interested in a 95% confidence interval, $\\alpha=0.05$, so we are looking for the $\\left(1-\\frac{0.05}{2}\\right)=0.975$^th^ quantile.\n\nWe can find these three values in R using the code below.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(potato_fertilised$yield)\nybar <- mean(potato_unfertilised$yield)\nz <- qnorm(0.975)\n```\n:::\n\n:::\n\nNow we can see in the **Environment** tab that $\\bar x=38.75$ tonnes, $\\bar y=38.6$ tonnes and $z_{0.975}=1.96$.\n\nCalculating the 95% confidence interval is now just a case of subbing in all the values into Equation \\eqref{eq:known-equal}. We can do this in R as follows.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*z*sigma*sqrt(1/nx + 1/ny)\n```\n:::\n\n\n## R Code with Output\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*z*sigma*sqrt(1/nx + 1/ny)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.9603676  1.2677138\n```\n\n\n:::\n:::\n\n:::\n\nUsing `c(-1, 1)` allows us to find the lower and upper limit of the confidence interval in one easy step. We would interpret this confidence interval by saying that we are 95% confident that the difference between the population mean yields of potatoes from fertilised and unfertilised fields lies in the interval $\\left[-0.9604,\\, 1.2677\\right]$.\n\nNote that this interval is not strictly positive i.e. it contains the value 0. This tells us that there is not sufficient evidence that the population mean potato yield from fertilised fields is any different from the population mean potato yield from unfertilised fields at the $\\alpha=0.05$ significance level.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 2: Using the `z.test()` function\n::::\n::::{.example-container}\nExactly the same result can be reached by using the function `z.test()`. This function runs through all the steps we manually calculated in the section above, so can speed up the process of finding a confidence interval. This function is part of the `PASWR2` package, so we need to load it into the R session. `z.test()` can take the following arguments,\n\n* `x =`: this is a vector containing the sample data taken from the first normal distribution.\n* `y =`: this is a vector containing the sample data taken from the second normal distribution.\n* `sigma.x =`: this is the standard deviation of the first normal distribution.\n* `sigma.y =`: this is the standard deviation of the second normal distribution.\n* `conf.level =`: the is the confidence level for the desired interval. It needs to be put in as a decimal, so for a 95% confidence interval, we would use `0.95` for example.\n\nThe code below uses `z.test()` to find the 95% confidence interval for the difference in population mean potato yield from fertilised and unfertilised fields. We use `$conf` at the end of the function to extract only the confidence interval. `z.test()` by itself will return additional results.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PASWR2)\n\nz.test(x = potato_fertilised$yield, y = potato_unfertilised$yield,\n       sigma.x = 4, sigma.y = 4, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.9603676  1.2677138\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nAgain, we would interpret this confidence interval by saying that we are 95% confident that the difference between the population mean yields of potatoes from fertilised and unfertilised fields lies in the interval $\\left[-0.9604,\\, 1.2677\\right]$.\n\nWe would again say that there is not sufficient evidence that the population mean potato yield from fertilised fields is any different from the population mean potato yield from unfertilised fields since this interval contains the value 0.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 3: Using the `zsum.test()` function\n::::\n::::{.example-container}\nAnother function contained in the `PASWR2` package that can be useful is the `zsum.test()` function. This allows you to calculate the same confidence interval, but rather than inputting the data from the sample itself, you input some summary statistics that you have either calculated or have been given to you as part of the question.\n\n`zsum.test()` is a good function to use if you are not given the data from the samples as part of a question, but rather some already calculated summary statistics.\n\nThe arguments that `zsum.test()` can take are,\n\n* `mean.x =`: this is the mean of the first sample. We have already calculated $\\bar x$ and saved it as `xbar`.\n* `mean.y =`: this is the mean of the second sample. We have already calculated $\\bar y$ and saved it as `ybar`.\n* `sigma.x =`: this is the standard deviation of the underlying normal distribution the first sample has been taken from. We know from the question that this is equal to 4 and we have saved it in the object `sigma`.\n* `sigma.y =`: this is the standard deviation of the underlying normal distribution the second sample has been taken from. We know from the question that this is equal to 4 and we have saved it in the object `sigma`.\n* `n.x =`: this is the size of the first sample. In the question this is $n_X=130$ and this is already saved as `nx`.\n* `n.y =`: this is the size of the second sample. In the question this is $n_Y=80$ and this is already saved as `ny`.\n* `conf.level =`: this is the confidence level for the desired interval. It needs to be put in as a decimal, so for a 95% confidence interval, we would use `0.95` for example.\n\nWe can input all of these values as arguments in the `zsum.test()` function to find the 95% confidence interval for the difference in population mean yield of potatoes from the fertilised and unfertilised fields. Again, we use `$conf` at the end of the function to extract only the confidence interval.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PASWR2)  #this line only needs to be run once in each R session\n\nzsum.test(mean.x = xbar, mean.y = ybar, sigma.x = sigma, sigma.y = sigma,\n          n.x = nx, n.y = ny, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.9603676  1.2677138\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nThis confidence interval tells us that we are 95% confident that the difference between the population mean yields of potatoes from fertilised and unfertilised fields lies in the interval $\\left[-0.9604,\\, 1.2677\\right]$. Once again, we see that this interval contains 0, so there is not sufficient evidence to suggest a difference in population mean potato yield exists between the fertilised and unfertilised fields when the significance level is $\\alpha=0.05$.\n::::\n:::\n\n### Variances are known and unequal (8.2.4) {#sec-known-unequal}\n\nIn the case where the variances of both distributions are known but are unequal, that is $\\sigma_X^2\\neq\\sigma_Y^2$, then a $(1-\\alpha)\\cdot100\\%$ confidence interval for the difference in the population means, $\\mu_X-\\mu_Y$, is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.12} \\label{eq:known-unequal}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-z_{1-\\frac{\\alpha}{2}}\\cdot\\sqrt{\\frac{\\sigma_X^2}{n_X}+\\frac{\\sigma_Y^2}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+z_{1-\\frac{\\alpha}{2}}\\cdot\\sqrt{\\frac{\\sigma_X^2}{n_X}+\\frac{\\sigma_Y^2}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation}\n```\n\n:::\n\n------------------------------------------------------------------------\n\nTo see some further examples of using this confidence interval, see [Section 8.2.4](https://read.kortext.com/reader/pdf/92741/470){target=\"_blank\"} of *Probability and Statistics with R*.\n\nFrom the exploratory analysis completed in [Lab 8](https://moodle.gla.ac.uk/pluginfile.php/9502911/mod_resource/content/2/03-eda.html#aim-2){target=\"_blank\"}, the yields of wheat from fertilised and unfertilised fields both approximately follow normal distributions, but with unequal variances. At this stage of the analysis, we're going to assume the population variances are known and are $\\sigma_{\\mbox{f}}^2=3^2$ for yields from fertilised fields, and $\\sigma_{\\mbox{uf}}^2=1^2$ for yields from unfertilised fields.\n\nThat is, we're assuming the wheat yields from fertilised fields follow a $N(\\mu_{\\mbox{f}},3^2)$ distribution and the wheat yields from unfertilised fields follow a $N(\\mu_{\\mbox{uf}}, 1^2)$ distribution.\n\nWe can then calculate a 95% confidence interval for the difference in population mean wheat yields from fertilised and unfertilised fields using Equation \\eqref{eq:known-unequal} above. This can be done, again, in a few different ways in R.\n\n:::{.example}\n::::{.example-header}\nMethod 1: Using R as a calculator\n::::\n::::{.example-container}\nIn order to use Equation \\eqref{eq:known-unequal}, we can start by saving all the values that we know from the question as objects in the **Environment** tab. That is, $n_X=90$, $n_Y=120$, $\\sigma_X=3$ and $\\sigma_Y=1$. \n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nnx <- 90\nny <- 120\nsigmax <- 3\nsigmay <- 1\n```\n:::\n\n:::\n\nIn order to use the formula for the confidence interval stated above, we still need to find $\\bar x$, $\\bar y$ and $z_{1-\\frac{\\alpha}{2}}$. We can find each of these using the code below.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(wheat_fertilised$yield)\nybar <- mean(wheat_unfertilised$yield)\nz <- qnorm(0.975)\n```\n:::\n\n:::\n\nNow we can see in the **Environment** tab that $\\bar x=23.8$ tonnes, $\\bar y=17.98$ tonnes and $z_{0.975}=1.96$.\n\nCalculating the 95% confidence interval is now just a case of subbing in all the values into Equation \\eqref{eq:known-unequal}. We can do this in R as follows.\n\n\n::: {.cell}\n\n:::\n\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*z*sqrt(sigmax^2/nx + sigmay^2/ny)\n```\n:::\n\n\n## R Code with Output\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*z*sqrt(sigmax^2/nx + sigmay^2/ny)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.174600 6.464806\n```\n\n\n:::\n:::\n\n:::\n\nWe would interpret this confidence interval by saying that we are 95% confident that the difference between the population mean yields of wheat from fertilised and unfertilised fields lies in the interval $\\left[5.1746,\\, 6.4648\\right]$.\n\nNote that this interval is strictly positive which means there is statistically significant evidence of a difference between the population mean yields of wheat from the two types of field at the 5% significance level.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 2: Using the `z.test()` function\n::::\n::::{.example-container}\nAs we have seen, the function `z.test()` from the `PASWR2` package is useful if we have been provided the data and know the variances of the two normal distributions that the groups follow.\n\nIn this case, we can use `z.test()` to calculate a 95% confidence interval for the difference in population mean wheat yields from fertilised and unfertilised fields as follows.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PASWR2)  #this line only needs to be run once in each R session\n\nz.test(x = wheat_fertilised$yield, y = wheat_unfertilised$yield,\n       sigma.x = 3, sigma.y = 1, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.174600 6.464806\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nAgain, we would interpret this confidence interval by saying that we are 95% confident that the difference between the population mean yields of wheat from fertilised and unfertilised fields lies in the interval $\\left[5.1746,\\, 6.4648\\right]$. We also see statistically significant evidence that there is a difference in these two population means at the 5% significance level.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 3: Using the `zsum.test()` function\n::::\n::::{.example-container}\nTo save us from having to use R as a calculator to find the confidence interval, we can use the function `zsum.test()` from the `PASWR2` package.\n\nWe already have saved in the **Environment** tab that,\n\n- `xbar`$=\\bar x=23.8$\n\n- `ybar`$=\\bar y=17.98$\n\n- `sigmax`$=\\sigma_X=3$\n\n- `sigmay`$=\\sigma_Y=1$\n\n- `nx`$=n_X=90$\n\n- `ny`$=n_Y=120$\n\nWe can then find the 95% confidence interval for the difference in population mean wheat yield from fertilised and unfertilised fields as follows.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PASWR2)  #this line only needs to be run once in each R session\n\nzsum.test(mean.x = xbar, mean.y = ybar, sigma.x = sigmax, sigma.y = sigmay,\n          n.x = nx, n.y = ny, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.174600 6.464806\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nThis function is mostly useful if we are not provided with the original sample data, but rather summary statistics.\n\nWe can again see that the confidence interval is $\\left[5.1746,\\, 6.4648\\right]$, so we say we are 95% confident that the difference between the population mean yields of wheat from fertilised and unfertilised fields lies in this interval and that there is statistically significant evidence of a difference in these two population means at the 5% significance level.\n::::\n:::\n\n\n### Variances are unknown and assumed equal (8.2.5) {#sec-unknown-equal}\n\nWhen random samples have been taken from two normal distributions where the variances are unknown but assumed to be equal, a $(1-\\alpha)\\cdot100\\%$ confidence interval for $\\mu_X-\\mu_Y$ is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.15} \\label{eq:unknown-equal}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-t_{1-\\frac{\\alpha}{2};\\nu_p}\\cdot s_p\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+t_{1-\\frac{\\alpha}{2};\\nu_p}\\cdot s_p\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation}\n```\n\n:::\n\n-   $\\nu_p$ represents the degrees of freedom for the associated $t$ distribution. The degrees of freedom can be found as $\\nu_p=n_X+n_Y-2$.\n\n-   $s_p$ is a pooled estimate of the standard deviation that takes into account the sample sizes, $n_X$ and $n_Y$, taken from each distribution. An estimate for the pooled **variance** can be found using, $$s_p^2=\\frac{\\left(n_X-1\\right)s_X^2+\\left(n_Y-1\\right)s_Y^2}{n_X+n_Y-2}$$\n\n    where, $s_X^2=\\frac{\\sum_{i=1}^{n_X}x_i^2-n_X\\bar x^2}{n_X-1}$ and $s_Y^2=\\frac{\\sum_{i=1}^{n_Y}y_i^2-n_Y\\bar y^2}{n_Y-1}$.\n\n    *Remember to take the square root of the estimated variance to find the estimate of standard deviation.*\n\n------------------------------------------------------------------------\n\nTo see more examples of calculating these confidence intervals, see [Section 8.2.5](https://read.kortext.com/reader/pdf/92741/474){target=\"_blank\"} of *Probability and Statistics with R*.\n\nSo far, when calculating the confidence interval for the difference in population mean yield of potatoes, we have been told the value for $\\sigma^2_X=\\sigma^2_Y=\\sigma^2$, the population variance. It might not be the case that we know this value, in which case we would use Equation \\eqref{eq:unknown-equal} stated above.\n\nThe difference between this one and Equation \\eqref{eq:known-equal} from [Section @sec-known-equal] is that the $t$-distribution is now used rather than the standard normal, and that a pooled estimate of the standard deviation is used. This is because we do not know a value for the population standard deviation $\\sigma$.\n\nWe don't actually know the standard deviations of the distributions that potato yields follow, but based on our exploratory analysis from [Lab 8](https://moodle.gla.ac.uk/pluginfile.php/9502911/mod_resource/content/2/03-eda.html#aim-1){target=\"_blank\"}, we can assume that they are equal. We also know that potato yields from both fertilised and unfertilised fields approximately follow normal distributions. Therefore, a 95% confidence interval for the difference in mean population potato yields from fertilised and unfertilised fields can be calculated using Equation \\eqref{eq:unknown-equal}. The confidence interval can be found in R in a few different ways.\n\n:::{.example}\n::::{.example-header}\nMethod 1: Using R as a calculator\n::::\n::::{.example-container}\nWe can start by saving $n_X=130$ and $n_Y=80$ as objects in the **Environment** tab.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nnx <- 130\nny <- 80\n```\n:::\n\n:::\n\nThen we can calculate $\\bar x$, $\\bar y$ and $t_{1-\\frac{\\alpha}{2};\\nu_p}$, which is the $(1-\\frac{\\alpha}{2})$^th^ quantile from the $t$-distribution with $\\nu_p=n_X+n_Y-2$ degrees of freedom. Because we are interested in a 95% confidence interval, $\\alpha=0.05$, so the quantile we are looking for is the $\\left(1-\\frac{0.05}{2}\\right)=0.975$^th^ quantile. To find a quantile from the $t$-distribution, we use the `qt()` function.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(potato_fertilised$yield)\nybar <- mean(potato_unfertilised$yield)\nt <- qt(0.975, nx + ny - 2)\n```\n:::\n\n:::\n\nIn order to use Equation \\eqref{eq:unknown-equal}, we also need to calculate the estimate for the pooled variance, $s_p^2$. Before we can do this, we need to find the sum of squares for both groups, $s_X^2$ and $s_Y^2$. This can be done using the code below, which first of all calculates $\\sum_{i=1}^{n_X}x_i^2$ and $\\sum_{i=1}^{n_Y}y_i^2$ and saves them as `sum_x2` and `sum_y2` respectively. These values are then used to find $s_X^2$ and $s_Y^2$, which have been saved as `s2x` and `s2y` respectively.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nsum_x2 <- sum(potato_fertilised$yield^2)\nsum_y2 <- sum(potato_unfertilised$yield^2)\n\ns2x <- (sum_x2 - nx*xbar^2)/(nx - 1)\ns2y <- (sum_y2 - ny*ybar^2)/(ny - 1)\n```\n:::\n\n:::\n\nNote that here we have calculated the variance of both groups 'by hand'. We could do exactly the same thing using the `var()` function, which calculates the variance of a vector of values.\n\nNow we can find the estimate for the pooled variance, $s_p^2$, using the values for the sum of squares for both groups. This has been saved as `sp2`.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nsp2 <- ((nx - 1)*s2x + (ny - 1)*s2y)/(nx + ny - 2)\n```\n:::\n\n:::\n\nNow we can sub all of the values that have been calculated into Equation \\eqref{eq:unknown-equal} as follows.\n\n\n::: {.cell}\n\n:::\n\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*t*sqrt(sp2)*sqrt(1/nx + 1/ny)\n```\n:::\n\n\n## R Code with Output\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*t*sqrt(sp2)*sqrt(1/nx + 1/ny)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.9695833  1.2769294\n```\n\n\n:::\n:::\n\n:::\n\nWe are 95% confident that the difference between the population mean yields of potatoes from fertilised and unfertilised fields lies in the interval $\\left[-0.9696,\\, 1.2769\\right]$ when the population variances are unknown, but assumed equal.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 2: Using the `t.test()` function\n::::\n::::{.example-container}\nAnother way in which we can calculate this 95% confidence interval is by using the `t.test()` function. This function is already part of R, so you don't need to load any packages. The only arguments that `t.test()` needs are,\n\n* `x =`: this is the vector of normally distributed values from the first group.\n* `y =`: this is the vector of normally distributed values from the second group.\n* `var.equal =`: this takes the value `TRUE` or `FALSE`, indicating whether we believe the variances, and hence the standard deviations, of both groups are the same.\n* `conf.level =`: this is the confidence interval for the desired interval. It needs to be put in as a decimal, so for a 95% confidence interval, we would use `0.95`.\n\nThe code below uses `t.test()` to find the 95% confidence interval for the difference in population mean potato yield from fertilised and unfertilised fields. `$conf` is used to extract only the confidence interval as by itself, `t.test()` will return additional results.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x = potato_fertilised$yield, y = potato_unfertilised$yield,\n       var.equal = TRUE, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.9695833  1.2769294\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nWe see the same result, that the 95% confidence interval for the difference in population mean potato yields from the two types of field is $\\left[-0.9696,\\, 1.2769\\right]$.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 3: Using the `tsum.test()` function\n::::\n::::{.example-container}\nIf we had been given summary statistics of the two groups, but did not know the variances of the groups, we can use the function `tsum.test()`. This is part of the `PASWR2` package, so make sure it is loaded into your R session.\n\nThe arguments that `tsum.test()` can take are,\n\n* `mean.x =`: this is the mean of the first sample, $\\bar x$.\n* `mean.y =`: this is the mean of the second sample, $\\bar y$.\n* `s.x =`: this is the estimate of the standard deviation of the first sample. We have already found the estimated variance, $s_X^2$, and saved it as `s2x`, so we just need to take the square root.\n* `s.y =`: this is the estimate of the standard deviation of the second sample. We have already found the estimated variance, $s_Y^2$, and saved it as `s2y`, so we just need to take the square root.\n* `n.x =`: this is the sample size of the first group, $n_X$.\n* `n.y =`: this is the sample size of the second group, $n_Y$.\n* `var.equal =`: this takes the value `TRUE` or `FALSE`, indicating whether we believe the variances, and hence the standard deviations, of both groups are the same.\n* `conf.level =`: this is the confidence interval for the desired interval.\n\nWe can input all of these values as arguments in the `tsum.test()` function to find the 95% confidence interval for the difference in population mean yield of potatoes from fertilised and unfertilised fields. Again, `$conf` is needed to show only the confidence interval.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PASWR2)  #this line only needs to be run once in each R session\n\ntsum.test(mean.x = xbar, mean.y = ybar, s.x = sqrt(s2x), s.y = sqrt(s2y),\n          n.x = nx, n.y = ny, var.equal = TRUE, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.9695833  1.2769294\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nOnce again, the 95% confidence interval returned to us for the difference between the population mean potato yield from fertilsied and from unfertilised fields is $\\left[-0.9696,\\, 1.2769\\right]$.\n::::\n:::\n\n::: question\n::: question-header\nTask\n:::\n::: {.question-container .webex-check}\n\n::: {.cell}\n\n:::\n\n\nHow would you interpret the 95% confidence interval for the difference in population mean potato yields between fertilised and unfertilised fields, when the variances are unknown but assumed equal? <div class='webex-radiogroup' id='radio_NFAXELCWDG'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NFAXELCWDG\" value=\"\"></input> <span>The population mean potato yield from fertilised fields is significantly higher than the population mean potato yield from unfertilised fields.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NFAXELCWDG\" value=\"answer\"></input> <span>There is not significant evidence to suggest a difference between the population mean potato yields from fertilised and unfertilised fields at the 5% significance level.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NFAXELCWDG\" value=\"\"></input> <span>There is significant evidence to suggest a difference between the population mean potato yields from fertilised and unfertilised fields at the 5% significance level.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NFAXELCWDG\" value=\"\"></input> <span>The population mean potato yield from fertilised fields is significantly lower than the population mean potato yield from unfertilised fields.</span></label></div>\n\n:::\n:::\n\n::: question\n::: question-header\nTask\n:::\n::: question-container\nOpen the statistical report you have saved from Lab 8. This should already contain complete **Introduction** and **Exploratory Analysis** sections.\n\nIn the **Statistical Analysis** section, add in an interpretation of the 95% confidence interval for the difference in population mean potato yields between fertilised and unfertilised fields. Make sure you state what the assumptions you have made to calculate this confidence interval are, the values in the interval and how this would be interpreted.\n:::\n:::\n\n\n### Variances are unknown and unequal (8.2.6) {#sec-unknown-unequal}\n\nWhen random samples have been taken from two normal distributions where the variances, $\\sigma_X^2$ and $\\sigma_Y^2$, are unknown and they are assumed unequal, a $(1-\\alpha)\\cdot100\\%$ confidence interval for $\\mu_X-\\mu_Y$ is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.16} \\label{eq:unknown-unequal}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-t_{1-\\frac{\\alpha}{2};\\nu}\\cdot \\sqrt{\\frac{s_X^2}{n_X}+\\frac{s_Y^2}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+t_{1-\\frac{\\alpha}{2};\\nu}\\cdot\\sqrt{\\frac{s_X^2}{n_X}+\\frac{s_Y^2}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation}\n```\n\n:::\n\n-   $\\nu$ represents the degrees of freedom for the associated $t$ distribution. The degrees of freedom can be found using, $$\\nu=\\frac{\\left(\\frac{s_X^2}{n_X}+\\frac{s_Y^2}{n_Y}\\right)^2}{\\frac{\\left(s_X^2/n_X\\right)^2}{n_X-1}+\\frac{\\left(s_Y^2/n_Y\\right)^2}{n_Y-1}}$$\n\n    where, $s_X^2=\\frac{\\sum_{i=1}^{n_X}x_i^2-n_X\\bar x^2}{n_X-1}$ and $s_Y^2=\\frac{\\sum_{i=1}^{n_Y}y_i^2-n_Y\\bar y^2}{n_Y-1}$.\n\n------------------------------------------------------------------------\n\nSee [Section 8.2.6](https://read.kortext.com/reader/pdf/92741/476){target=\"_blank\"} of *Probability and Statistics with R* for further examples of finding these confidence intervals.\n\nThe standard deviations of the distributions that wheat yields follow are not actually known and from the exploratory analysis, it seems that the population variances are likely unequal. Assuming this is the case, we can still calculate a 95% confidence interval for the difference in population mean wheat yield between fertilised and unfertilised fields using Equation \\eqref{eq:unknown-unequal} above.\n\nIn order to use this result, both groups must be normally distributed. We have already seen that this is the case from the exploratory analysis, but if we hadn't checked **make sure to check both groups follow a normal distribution**, using QQ plots.\n\nThere a few different ways in which we can calculate the desired 95% confidence interval.\n\n:::{.example}\n::::{.example-header}\nMethod 1: Using R as a calculator\n::::\n::::{.example-container}\nWe start by saving $n_X=90$ and $n_Y=120$ as objects in the **Environment** tab and calculating the mean of each group.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nnx <- 90\nny <- 120\n\nxbar <- mean(wheat_fertilised$yield)\nybar <- mean(wheat_unfertilised$yield)\n```\n:::\n\n:::\n\nWe can see now, in the **Environment** tab, that $\\bar x=23.8$ and $\\bar y=17.98$.\n\nBefore we can find the $\\left(1-\\frac{\\alpha}{2}\\right)$^th^ quantile from the $t$-distribution, we need to find the associated degrees of freedom $\\nu$. This involves a few steps. First of all, we find $\\sum_{i=1}^{n_X}x_i^2$ and $\\sum_{i=1}^{n_Y}y_i^2$.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nsum_x2 <- sum(wheat_fertilised$yield^2)\nsum_y2 <- sum(wheat_unfertilised$yield^2)\n```\n:::\n\n:::\n\nRunning the above code will show us that $\\sum_{i=1}^{n_X}x_i^2=5.171523\\times 10^{4}$ and $\\sum_{i=1}^{n_Y}y_i^2=3.893489\\times 10^{4}$. We can use these values to find the variance of the two wheat yield samples, $s_X^2$ and $s_Y^2$.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ns2x <- (sum_x2 - nx*xbar^2)/(nx - 1)\ns2y <- (sum_y2 - ny*ybar^2)/(ny - 1)\n```\n:::\n\n:::\n\nIf we had used the `var()` function we would be left with the same result, that $s_X^2=8.21$ and $s_Y^2=1.13$. Now we can use these values to find $\\nu$ as follows (this value is saved as `df`) and find the $\\left(1-\\frac{\\alpha}{2}\\right)$^th^ quantile from the $t$-distribution with $\\nu$ degrees of freedom using the function `qt()`.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- (s2x/nx + s2y/ny)^2 / ((s2x/nx)^2/(nx-1) + (s2y/ny)^2/(ny - 1))\n\nt <- qt(0.975, df)\n```\n:::\n\n:::\n\nFinally, we can sub all of these values into the formula for the confidence interval.\n\n\n::: {.cell}\n\n:::\n\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*t*sqrt(s2x/nx + s2y/ny)\n```\n:::\n\n\n## R Code with Output\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*t*sqrt(s2x/nx + s2y/ny)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.190980 6.448426\n```\n\n\n:::\n:::\n\n:::\n\nWe would interpret this interval by saying that we are 95% confident that the difference between the population mean wheat yield from fertilised and unfertilised fields lies in the interval $\\left[5.191,\\, 6.4484\\right]$. This is true for the scenario where we don't know the variance of each underlying distribution and assume it is different for the two groups.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 2: Using the `t.test()` function\n::::\n::::{.example-container}\nWe can find the same interval using the `t.test()` function.\n\nTo find the 95% confidence interval for the difference in population mean wheat yields from fertilised and unfertilised fields, assuming the variances are unequal, we would use the code below.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(x = wheat_fertilised$yield, y = wheat_unfertilised$yield,\n       var.equal = FALSE, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.190980 6.448426\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nThis again tells us that the interval is $\\left[5.191,\\, 6.4484\\right]$, so we are 95% confident the difference in population mean wheat yields from fertilised and unfertilised fields lies in this interval.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 3: Using the `tsum.test()` function\n::::\n::::{.example-container}\nWe could also use the summary statistics, already calculated, and the function `tsum.test()` from the `PASWR2` package. This would look as follows.\n\n::: panel-tabset\n## R Code\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PASWR2)  #this line only needs to be run once in each R session\n\ntsum.test(mean.x = xbar, mean.y = ybar, s.x = sqrt(s2x), s.y = sqrt(s2y),\n          n.x = nx, n.y = ny, var.equal = FALSE, conf.level = 0.95)$conf\n```\n:::\n\n\n## Output\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.190980 6.448426\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nWe would say that we are 95% confident that the difference in population mean yields of wheat from the two types of field lies in the interval $\\left[5.191,\\, 6.4484\\right]$.\n::::\n:::\n\n::: question\n::: question-header\nTask\n:::\n::: {.question-container .webex-check}\n\n::: {.cell}\n\n:::\n\n\nHow would you interpret the 95% confidence interval for the difference in population mean wheat yields between fertilised and unfertilised fields, when the variances are unknown and assumed unequal? <div class='webex-radiogroup' id='radio_NMPKAKHFCG'><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NMPKAKHFCG\" value=\"answer\"></input> <span>There is significant evidence to suggest a difference between the population mean wheat yields from fertilised and unfertilised fields at the 5% significance level.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NMPKAKHFCG\" value=\"\"></input> <span>There is not significant evidence to suggest a difference between the population mean wheat yields from fertilised and unfertilised fields at the 5% significance level.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NMPKAKHFCG\" value=\"\"></input> <span>The population mean wheat yield from fertilised fields is significantly lower than the population mean wheat yield from unfertilised fields.</span></label><label><input type=\"radio\" autocomplete=\"off\" name=\"radio_NMPKAKHFCG\" value=\"\"></input> <span>The population mean wheat yield from fertilised fields is equal to the population mean wheat yield from unfertilised fields at the 5% significance level.</span></label></div>\n\n:::\n:::\n\n::: question\n::: question-header\nTask\n:::\n::: question-container\nIn the **Statistical Analysis** section of your report, add in an interpretation of the 95% confidence interval for the difference in population mean wheat yields between fertilised and unfertilised fields.\n\nMake sure you state what the assumptions you have made to calculate this confidence interval are, the values in the interval and how this would be interpreted.\n:::\n:::\n\n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}