---
title: "Writing A Report"
number-sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE, comment=NA)
library(webexercises)
library(PASWR2)
library(knitr)
library(kableExtra)
library(ggplot2)
library(tidyverse)
```

When writing a formal statistical report, there is a typical structure that helps ensure all relevant information is included in a sensible way. By using the following sections, your report will flow well and detail your analysis in full.

A template for a general statistical report, using the following structure, is included at the top of the Lab section on [Moodle](https://moodle.gla.ac.uk/course/view.php?id=43654&section=9){target="_blank"} which you can always use for reference.

::: webex-highlight
1.  [**Introduction**](02-intro.qmd): this is where you should write a short description of the problem and provide context such as the data and variables collected. The aims of the analysis should also be clearly stated here.

2.  [**Exploratory Analysis**](03-eda.qmd): this is where you should include appropriate summary statistics and plots you've created from the data. These should provide an initial impression and informally answer the aims of your analysis. Any tables and/or figures included should always be clearly captioned.

3.  **Statistical Analysis**: this is where the aims of the analysis will be formally answered. Describe the statistical methods and techniques you will use to analyse the data and detail any assumption you are making about the data. Include any relevant *output* from the analysis you've completed (you should *not include any code* from your R script in a report) and interpret the output in the context of the problem.

4.  **Conclusion**: use your interpretation to provide an answer to the aims of the analysis. Discuss how this formal conclusion compares to the initial impressions of the data from the Exploratory Analysis and discuss any limitations in your analysis, for example, are there any other techniques you may use in further analysis to provide a better result?
:::

In this lab we will focus on sections (1) and (2) of the report. Sections (3) and (4) will be discussed in Lab 9.

::: question
::: question-header
Task
:::

::: question-container
For this lab, we want to start to produce a statistical report detailing the analysis we will work through. A template for a general statistical report is provided on [Moodle](https://moodle.gla.ac.uk/course/view.php?id=43654&section=9#module-4463040){target="_blank"}. Download this template and save it somewhere you are able to access it. We will add to the template throughout this lab.
:::
:::
