---
title: "Introduction"
number-sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, eval=TRUE, comment=NA)
library(webexercises)
library(PASWR2)
library(knitr)
library(kableExtra)
library(ggplot2)
library(tidyverse)
```

Every statistical analysis needs a problem to answer. For this lab, we will focus on the example given by the data set *yields.csv* on **Moodle**.

## Background to the problem

A group of farmers is interested in whether a specific fertiliser will increase their annual yield of potatoes and wheat. They apply the new fertiliser to a total of 130 fields where potatoes are grown and 90 fields where wheat is grown. They measure the yield (in tonnes) from each field.

An additional 80 potato fields and 120 wheat fields were left unfertilised and the yields of crops from these fields was also recorded (in tonnes).

The farmers want to use the yields they have measured from their fields to assess whether the fertiliser has any significant affect on their crop yields.

## Aims {#sec-aims}

Before starting to look at the data in any detail, it is important to think about the **aims** of our analysis. These often take the form of questions we want to answer.

::: webex-highlight
For our farming example, these might be questions such as;

1.  Is there a difference between the mean yields of potatoes from fields that were fertilised and fields that were unfertilised?

2.  Is there a difference between the mean yields of wheat from fields that were fertilised and fields that were unfertilised?

<!--3.   What proportion of field's yields might the farmers expect to sell to supermarkets?-->
:::

::: question
::: question-header
Task
:::

::: question-container
Now that we know the background of our analysis, give your statistical report a sensible title. This should be informative and give an overview of the context of our report.
:::
:::

::: question
::: question-header
Task
:::

::: question-container
In your statistical report template, write an **Introduction** section. Make sure that this clearly provides some background to the analysis and describes what has been measured in the data gathered. Also ensure that you clearly state the aims of the analysis.
:::
:::
