project:
  type: book
  output-dir: docs

book:
  title: "S2S Lab 1"
  chapters:
    - index.qmd
    - 01-vectors.qmd
    - 02-exercises.qmd
    - 03-summary.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    css: 
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
    embed-resources: true


editor: source

