project:
  type: book
  output-dir: docs

book:
  title: "S2S Lab 2"
  chapters:
    - index.qmd
    - 01-packages.qmd
    - 02-data.qmd
    - 03-exercises.qmd
    - 04-summary.qmd
  appendices: 
    - 05-dimensions.qmd
    - 06-lists.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    css: 
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
    embed-resources: true


editor: visual

