project:
  type: book
  output-dir: docs

book:
  title: "Maximum Likelihood Estimation"
  chapters:
    - index.qmd
    - normal.qmd

format:
  html:
    theme: [cosmo, custom.scss]
    css: 
    - styles.css
    - include/webex.css
    toc: true
    include-after-body: include/webex.js
    embed-resources: true


editor: source

