---
title: "S2S Lab 6"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=TRUE, comment=NA)
library(webexercises)
library(ggplot2)
```

# Welcome!

Welcome to the sixth S2S lab. This lab expands on the concept of sampling distributions (introduced in [Lab 5](https://s2s-statistical-mm-c-1.github.io/Labs/S2SLab5/docs/)) to look at the scenario of sampling from continuous distributions other than the normal distribution. To help us do this, we introduce an important result in statistics know as the central limit theorem. This section of the lab follows Section [6.5.1.2 Second Case: Sampling Distribution of $\bar X$ When $X$ Is Not a Normal Random Variable](https://read.kortext.com/reader/pdf/92741/370) of *Probability and Statistics with R*.

We will also look at creating a sampling distribution for the difference between two means, when both of the orginal random variables do come from a normal distribution. This second section of the lab is based on Section [6.5.2 Sampling Distribution for $\bar X - \bar Y$ When Sampling from Two Independent Normal Populations](https://read.kortext.com/reader/pdf/92741/375) of *Probability and Statistics with R*.