{
  "hash": "7961bb9cc334b54aad07a1863b387dc2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Statistical Analysis\"\n---\n\n\n\n\n\n\n\nThe two [aims](index.qmd) of our analysis both ask whether there is a difference between the means of two groups of data. This is something that we can use confidence intervals to find.\n\n# Difference in Population Means {#sec-diff}\n\n<!-- # Confidence Intervals for the Difference in Population Means -->\n\nIn general, when we have two independent random variables which both follow normal distributions, say $X\\sim N(\\mu_X,\\,\\sigma_X)$ and $Y\\sim N(\\mu_Y,\\,\\sigma_Y)$, it is often of interest to find a range of values for the difference between the population means, $\\mu_X$ and $\\mu_Y$. This range of values can be found using a confidence interval for $\\mu_X-\\mu_Y$, but we have to be aware of the variances of both distributions, as this can change the way the confidence interval is calculated. In order to construct these confidence intervals, random samples have to be drawn from the underlying distributions.\n\nWe will use the following notation in the formulae for confidence intervals for the difference in population means,\n\n- $n_X$: the size of the sample drawn from $X\\sim N(\\mu_X,\\,\\sigma_X)$.\n- $n_Y$: the size of the sample drawn from $Y\\sim N(\\mu_Y,\\,\\sigma_Y)$.\n- $x_1, x_2, \\ldots , x_{n_X}$: the sample taken from $X\\sim N(\\mu_X,\\,\\sigma_X)$ with sample mean $\\bar{x}$ and sample variance $s^2_X$.\n- $y_1, y_2, \\ldots , y_{n_Y}$: the sample taken from $Y\\sim N(\\mu_Y,\\,\\sigma_Y)$ with sample mean $\\bar{y}$ and sample variance $s^2_Y$.\n\n## Variances are known and equal (8.2.3) {#sec-known-equal}\n\nIn the case where the variances of both distributions are known and are equal, that is $\\sigma_X^2=\\sigma_Y^2=\\sigma^2$, then a $(1-\\alpha)\\cdot100\\%$ confidence interval for the difference in the population means, $\\mu_X-\\mu_Y$, is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.11}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-z_{1-\\frac{\\alpha}{2}}\\cdot\\sigma\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+z_{1-\\frac{\\alpha}{2}}\\cdot\\sigma\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation}\n```\n\n:::\n\n------------------------------------------------------------------------\n\nYou can find the derivation of this result and some additional exercises in [Section 8.2.3](https://read.kortext.com/reader/pdf/92741/466) of *Probability and Statistics with R*.\n\n### Aim 1 {#sec-pot-knownvar}\n\nWe saw from the Exploratory Analysis completed in [Lab 8]() that the yields of potatoes from fertilised and unfertilised fields both seem to follow a normal distribution with approximately equal variances. To simplify our analysis at this stage, let's first assume that the population variances are known and are equal to $\\sigma^2_\\mbox{f}=\\sigma^2_\\mbox{uf}=4^2$.\n\nThat is, we are assuming that the yield of potatoes from fertilised fields follows a $N(\\mu_\\mbox{f},4)$ distribution, and the yield of potatoes from unfertilised fields follows a $N(\\mu_\\mbox{uf}, 4)$ distribution.\n\nNow we are ready to compute a 95% confidence interval for the difference in population mean yields of potatoes from fields that were fertilised and fields that were unfertilised. That is, a confidence interval for $\\mu_\\mbox{f}-\\mu_\\mbox{uf}$. There a few different ways we could do this in R.\n\n:::{.example}\n::::{.example-header}\nMethod 1: Using R as a calculator\n::::\n::::{.example-container}\nIn order to use the formula for the confidence interval stated above, there are a few values we need to find. we have already assumed that $\\sigma=4$, and we know that $n_X=130$ and $n_Y=80$. We can save these values in R using the code below.\n\n::: panel-tabset\n## R Script\n\n::: {.cell}\n\n```{.r .cell-code}\nsigma <- 4\nnx <- 130\nny <- 80\n```\n:::\n\n:::\n\nThat leaves us to find $\\bar x$, $\\bar y$ and $z_{1-\\frac{\\alpha}{2}}$, the $(1-\\frac{\\alpha}{2})$^th^ quantile from the standard normal distribution. In our case, because we are interested in a 95% confidence interval, $\\alpha=0.05$, so we are looking for the $\\left(1-\\frac{0.05}{2}\\right)=0.975$^th^ quantile.\n\nWe can find these three values in R using the code below.\n\n::: panel-tabset\n## R Script\n\n::: {.cell}\n\n```{.r .cell-code}\nxbar <- mean(potato_fertilised$yield)\nybar <- mean(potato_unfertilised$yield)\nz <- qnorm(0.975)\n```\n:::\n\n:::\n\nNow we can see in the **Environment** tab that $\\bar x=38.75$ tonnes, $\\bar y=37.6$ tonnes and $z_{0.975}=1.96$.\n\nCalculating the 95% confidence interval is now just a case of subbing in all the values into the formula shown above. We can do this in R as follows.\n\n::: panel-tabset\n## R Script\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n(xbar - ybar) + c(-1, 1)*z*sigma*sqrt(1/nx + 1/ny)\n```\n:::\n\n\n## Console\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03963237 2.26771378\n```\n\n\n:::\n:::\n\n:::\n\nUsing `c(-1, 1)` allows us to find the lower and upper limit of the confidence interval in one easy step. We would interpret this confidence interval by saying that we are 95% confident that the difference between the average yields of potatoes from fertilised and unfertilised fields lies in the interval $\\left[0.0396,\\, 2.2677\\right]$.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 2: Using the `z.test()` function\n::::\n::::{.example-container}\nExactly the same result can be reached by using the function `z.test()`. This function runs through all the steps we manually calculated in the section above, so can speed up the process of finding a confidence interval. This function is part of the `PASWR2` package, so we need to load it into the R session. `z.test()` can take the following arguments,\n\n* `x =`: this is a vector containing the sample data taken from the first normal distribution.\n* `y =`: this is a vector containing the sample data taken from the second normal distribution.\n* `sigma.x =`: this is the standard deviation of the first normal distribution.\n* `sigma.y =`: this is the standard deviation of the second normal distribution.\n* `conf.level =`: the is the confidence level for the desired interval. It needs to be put in as a decimal, so for a 95% confidence interval, we would use `0.95` for example.\n\nThe code below uses `z.test()` to find the 95% confidence interval for the difference in population mean potato yield from fertilised and unfertilised fields. We use `$conf` at the end of the function to extract only the confidence interval. `z.test()` by itself will return additional results.\n\n::: panel-tabset\n## R Script\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(PASWR2)\n\nz.test(x = potato_fertilised$yield, y = potato_unfertilised$yield,\n       sigma.x = 4, sigma.y = 4, conf.level = 0.95)$conf\n```\n:::\n\n\n## Console\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03963237 2.26771378\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nAgain, we would interpret this confidence interval by saying that we are 95% confident that the difference between the average yields of potatoes from fertilised and unfertilised fields lies in the interval $\\left[0.0396,\\, 2.2677\\right]$.\n::::\n:::\n\n:::{.example}\n::::{.example-header}\nMethod 3: Using the `zsum.test()` function\n::::\n::::{.example-container}\nAnother function contained in the `PASWR2` package that can be useful is the `zsum.test()` function. This allows you to calculate the same confidence interval, but rather than inputting the data from the sample itself, you input some summary statistics that you have either calculated or have been given to you as part of the question.\n\n`zsum.test()` is a good function to use if you are not given the data from the samples as part of a question, but rather some already calculated summary statistics.\n\nThe arguments that `zsum.test()` can take are,\n\n* `mean.x =`: this is the mean of the first sample. We have already calculated $\\bar x$ and saved it as `xbar`.\n* `mean.y =`: this is the mean of the second sample. We have already calculated $\\bar y$ and saved it as `ybar`.\n* `sigma.x =`: this is the standard deviation of the underlying normal distribution the first sample has been taken from. We know from the question that this is equal to 4 and we have saved it in the object `sigma`.\n* `sigma.y =`: this is the standard deviation of the underlying normal distribution the second sample has been taken from. We know from the question that this is equal to 4 and we have saved it in the object `sigma`.\n* `n.x =`: this is the size of the first sample. In the question this is $n_X=13$ and this is already saved as `nx`.\n* `n.y =`: this is the size of the second sample. In the question this is $n_Y=8$ and this is already saved as `ny`.\n* `conf.level =`: this is the confidence level for the desired interval. It needs to be put in as a decimal, so for a 95% confidence interval, we would use `0.95` for example.\n\nWe can input all of these values as arguments in the `zsum.test()` function to find the 95% confidence interval for the difference in population mean yield of potatoes from the fertilised and unfertilised fields. Again, we use `$conf` at the end of the function to extract only the confidence interval.\n\n::: panel-tabset\n## R Script\n\n::: {.cell}\n\n```{.r .cell-code}\nzsum.test(mean.x = xbar, mean.y = ybar, sigma.x = sigma, sigma.y = sigma,\n          n.x = nx, n.y = ny, conf.level = 0.95)$conf\n```\n:::\n\n\n## Console\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03963237 2.26771378\nattr(,\"conf.level\")\n[1] 0.95\n```\n\n\n:::\n:::\n\n:::\n\nThis confidence interval tells us that we are 95% confident that the difference between the average yields of potatoes from fertilised and unfertilised fields lies in the interval $\\left[0.0396,\\, 2.2677\\right]$.\n::::\n:::\n\n## Variances are known and unequal (8.2.4) {#sec-known-unequal}\n\nIn the case where the variances of both distributions are known and but are unequal, that is $\\sigma_X^2\\neq\\sigma_Y^2$, then a $(1-\\alpha)\\cdot100\\%$ confidence interval for the difference in the population means, $\\mu_X-\\mu_Y$, is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.12}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-z_{1-\\frac{\\alpha}{2}}\\cdot\\sqrt{\\frac{\\sigma_X^2}{n_X}+\\frac{\\sigma_Y^2}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+z_{1-\\frac{\\alpha}{2}}\\cdot\\sqrt{\\frac{\\sigma_X^2}{n_X}+\\frac{\\sigma_Y^2}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation}\n```\n\n:::\n\n------------------------------------------------------------------------\n\nTo see some further examples of using this confidence interval, see [Section 8.2.4](https://read.kortext.com/reader/pdf/92741/470) of *Probability and Statistics with R*.\n\n## Variances are unknown and assumed equal (8.2.5) {#sec-unknown-equal}\n\nWhen random samples have been taken from two normal distributions where the variances are unknown but assumed to be equal, a $(1-\\alpha)\\cdot100\\%$ confidence interval for $\\mu_X-\\mu_Y$ is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.15}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-t_{1-\\frac{\\alpha}{2};\\nu_p}\\cdot s_p\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+t_{1-\\frac{\\alpha}{2};\\nu_p}\\cdot s_p\\sqrt{\\frac{1}{n_X}+\\frac{1}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation}\n```\n\n:::\n\n-   $\\nu_p$ represents the degrees of freedom for the associated $t$ distribution. The degrees of freedom can be found as $\\nu_p=n_X+n_Y-2$.\n\n-   $s_p$ is a pooled estimate of the standard deviation that takes into account the sample sizes, $n_X$ and $n_Y$, taken from each distribution. An estimate for the pooled **variance** can be found using, $$s_p^2=\\frac{\\left(n_X-1\\right)s_X^2+\\left(n_Y-1\\right)s_Y^2}{n_X+n_Y-2}$$\n\n    where, $s_X^2=\\frac{\\sum_{i=1}^{n_X}x_i^2-n_X\\bar x^2}{n_X-1}$ and $s_Y^2=\\frac{\\sum_{i=1}^{n_Y}y_i^2-n_Y\\bar y^2}{n_Y-1}$.\n\n    *Remember to take the square root of the estimated variance to find the estimate of standard deviation.*\n\n------------------------------------------------------------------------\n\nTo see more examples of calculating these confidence intervals, see [Section 8.2.5](https://read.kortext.com/reader/pdf/92741/474) of *Probability and Statistics with R*.\n\n## Variances are unknown and unequal (8.2.6) {#sec-unknown-unequal}\n\nWhen random samples have been taken from two normal distributions where the variances, $\\sigma_X^2$ and $\\sigma_Y^2$, are unknown and they are unequal, a $(1-\\alpha)\\cdot100\\%$ confidence interval for $\\mu_X-\\mu_Y$ is given by,\n\n::: {.webex-highlight}\n\n```{=tex}\n\\begin{equation} \\tag{8.16}\n\\begin{split}\nCI_{1-\\alpha}(\\mu_X-\\mu_Y)=\\Bigg[&\\left(\\bar x-\\bar y\\right)-t_{1-\\frac{\\alpha}{2};\\nu}\\cdot \\sqrt{\\frac{s_X^2}{n_X}+\\frac{s_Y^2}{n_Y}},\\\\\n&\\,\\,\\,\\,\\,\\,\\,\\left(\\bar x-\\bar y\\right)+t_{1-\\frac{\\alpha}{2};\\nu}\\cdot\\sqrt{\\frac{s_X^2}{n_X}+\\frac{s_Y^2}{n_Y}}\\,\\Bigg]\n\\end{split}\n\\end{equation}\n```\n\n:::\n\n-   $\\nu$ represents the degrees of freedom for the associated $t$ distribution. The degrees of freedom can be found using, $$\\nu=\\frac{\\left(\\frac{s_X^2}{n_X}+\\frac{s_Y^2}{n_Y}\\right)^2}{\\frac{\\left(s_X^2/n_X\\right)^2}{n_X-1}+\\frac{\\left(s_Y^2/n_Y\\right)^2}{n_Y-1}}$$\n\n    where, $s_X^2=\\frac{\\sum_{i=1}^{n_X}x_i^2-n_X\\bar x^2}{n_X-1}$ and $s_Y^2=\\frac{\\sum_{i=1}^{n_Y}y_i^2-n_Y\\bar y^2}{n_Y-1}$.\n\n------------------------------------------------------------------------\n\nSee [Section 8.2.6](https://read.kortext.com/reader/pdf/92741/476) of *Probability and Statistics with R* for further examples of finding these confidence intervals.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}